targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
      freezed:
        generate_for:
          include:
            - lib/data/dto/**.dart
